theme: jekyll-theme-midnight
title: "eTracker: Exercise Your Freedom"
description: "Take control of your health! With eTracker, you will be guided to obtain the weight or health of your desire! Tracking "
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
